### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by narcolepticinsomniac** [OpenUserCSS/openusercss.org#19]
When you get the chance, hook up that forum section for Stylus. We'll probably be pushing an update sometime soon, so maybe we can switch up the help links beforehand. No rush though, just a reminder.

Also, a little detail, you shouldn't use `html { overflow-y: scroll; }` unless it's absolutely necessary for some weird reason. You're forcing useless scrollbars which is a bad look. `auto` is almost always sufficient, without the drawbacks.

**Comment by DecentM** [comment]
Done and done! Try posting something and moderating your post. Let me know if it's missing some feature or if you need anything else.

I'm forcing overflow because otherwise, the viewport jumps left and right when navigating between pages that have enough content to not fit the first fold and ones that do.
Try it out by removing the style definition in devtools and then clicking search and then home. If you have a solution that solves this, I'd be glad to implement it, but I think this works. I don't think that there are going to be loads of pages without scrolling anyway.

**Comment by DecentM** [comment]
This is usually not a problem for standard websites, but SPA-s with navigation animations have this quirk.

**Comment by narcolepticinsomniac** [comment]
LGTM. Don't I get a snazzy mod label? I like to feel important. =) I'll see if I can't get tophf to join.

Yeah, I figured you might've done it for a reason. NBD, but I'll check out that scenario you're referring to.

**Comment by DecentM** [comment]
You should have a label

**Comment by narcolepticinsomniac** [comment]
Don't see anything, do you? Cleared the cache, signed back in, still don't. I was mostly joking, but maybe it is a little bug.

**Comment by DecentM** [comment]
I just probably didn't set it up right. I'll take a look tomorrow.

**Comment by narcolepticinsomniac** [comment]
Yeah man, not the highest priority thing you have to work on.

**Comment by narcolepticinsomniac** [comment]
Took a look at the overflow. I've hacked up a pure CSS fix for a similar scrollbar issue in the past. If you're willing to sacrifice a practically undetectable fraction of overall centering, you can eliminate shifting when unnecessary scrollbars are removed. Try this example style:

```
@-moz-document url-prefix("https://openusercss.org/") {
html {
    overflow-y: auto!important;
    padding: 0 0 0 calc((100vw - 100%) * .5);
    width: calc(100vw - (100vw - 100%))!important;
}
nav:before,
nav:after {
    display: block;
    top: 0;
    content: '';
    width: calc((100vw - 100%) * .5);
    height: 100%;
    background: inherit;
    position: absolute;
}
nav:before {
    margin-left: calc(((100vw - 100%) * .5) * -1);
    box-shadow: inherit;
}
nav:after {
    margin-left: 0;
}
}

@-moz-document url-prefix("https://forums.openusercss.org/") {
html {
    overflow-y: auto!important;
}
.navbar,
#panel {
    padding-left: calc(100vw - 100%);
}
}
```

With access to the html, you could likely do something similar much more elegantly. It's all about the calcs and which elements they can be used on. The one for the forum is more straightforward, whereas the main site has a much more complicated layout in terms of changing `display`, `position` and sizing properties. Combined with the pushState type of loading and effects, it's quite a bit more intricate than a typical site. Given the fact that I don't have access to easily experiment with more elegant solutions, I fixed the header with a pseudo-element hack. The second pseudo is just to mask box-shadow.

Only tested in Chrome. Really just intended as an example, but it works pretty well. Hopefully the basic formula is useful.

**Comment by DecentM** [comment]
I put the scrollbar matter into #30, so that I can close this one, because forum badges now work :tada:
